name: Format
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.repository == 'Widen/i18next-async-backend'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install --immutable
      - run: yarn prettier --write .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
